#TODO: Consider Adding patients Data.

from scripts.extract import extract_pubmed_to_mongo
from scripts.transform.annotate import annotate_mongo_articles
from scripts.transform.clean import prepare_data_for_neo4j
from scripts.load import load_to_aura

from config.neo4jdb_config import NEO4J_LABELS, NEO4J_REL_TYPES

#paths
extracted_entities = "data/extracted_entities.csv"
extracted_relations = "data/extracted_relations.csv"
saving_dir = "data/ready_for_neo4j"


#less max_results, less API pression, more loop iterations
#if max results is not specified, the default is 1k, the max is 10k
#extract_abstracts_only = False to get also bodies for each article if available in PubMedCentral
extract_pubmed_to_mongo(extract_abstracts_only=True, max_results=1000)  

#this runs NER, RE, and Linking (normalization), and saves extracted entities and relations 
#to two separate csv files.
annotate_mongo_articles()

#this takes the csvs from the last step and prepare them to Neo4j
#it returns a tuple of (cleaned entities path, cleaned relations path)
clean_paths = prepare_data_for_neo4j(raw_ents_path=extracted_entities,
                       raw_rels_path=extracted_relations, 
                       saving_dir=saving_dir)

#this takes the cleaned csvs generated by the previous step and load their data to Neo4j as a graph.
#we can choose to load only entities (nodes), or only relations, or both.
load_to_aura(labels_to_load=NEO4J_LABELS, ents_clean_csv=clean_paths[0], 
             reltypes_to_load=NEO4J_REL_TYPES, rels_clean_csv=clean_paths[1])