#these are the entities recognized by the NER model
NEO4J_LABELS = ['AMINO_ACID',
                'ANATOMICAL_SYSTEM',
                'CANCER',
                'CELL',
                'CELLULAR_COMPONENT',
                'DEVELOPING_ANATOMICAL_STRUCTURE',
                'GENE_OR_GENE_PRODUCT',
                'IMMATERIAL_ANATOMICAL_ENTITY',
                'MULTI_TISSUE_STRUCTURE',
                'ORGAN',
                'ORGANISM',
                'ORGANISM_SUBDIVISION',
                'ORGANISM_SUBSTANCE',
                'PATHOLOGICAL_FORMATION',
                'SIMPLE_CHEMICAL',
                'TISSUE']

#relations we defined in config/nlp_config
NEO4J_REL_TYPES = ['PRODUCES',
                   'CONTAINS',
                   'BINDS',
                   'REGULATES',
                   'EXPRESSED_IN',
                   'MUTATED_IN',
                   'PART_OF',
                   'LOCATED_IN',
                   'ORIGIN_OF',
                   'CONTAINS_COMPONENT',
                   'SURROUNDS',
                   'DEVELOPS_INTO',
                   'ORIGINATES_FROM',
                   'ARISES_FROM',
                   'AFFECTS',
                   'ASSOCIATED_WITH',
                   'DAMAGES',
                   'BIOMARKER_FOR',
                   'TOXIC_TO',
                   'COMPONENT_OF',
                   'SECRETED_BY',
                   'TREATS']